on:
  push:
    branches:
      - 'feat/**'
      - 'features/**'
      - 'fix/**'
      - 'docs/**'
      - 'ci/**'
      - 'test/**'

name: 🔎 [VERSION] Peut on créer un nouveau tag ?
jobs:
  test-tag-avaibility:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Récupération de la version dans le `package.json` de la branche '${{ github.event.pull_request.head.ref }}'.
        id: current_version
        run: |
          $version = (Get-Content package.json | ConvertFrom-Json).version
          echo "CURRENT_VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Récupération de la version dans le `package.json` de la branche 'main'.
        id: main_version
        run: |
          $version = (Get-Content package.json | ConvertFrom-Json).version
          echo "MAIN_VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Debug.
        run: |
          echo "Current branch version: ${{ env.CURRENT_VERSION }}"
          echo "Main branch version: ${{ env.MAIN_VERSION }}"

      - name: Comparaison des versions.
        uses: actions/github-script@v7
        if: env.CURRENT_VERSION == env.MAIN_VERSION
        with:
          script: |
            core.setFailed("La version dans package.json n'a pas été mise à jour. Veuillez mettre à jour la version. N'oubliez pas de vérifier le CHANGELOG et le README également.")

      - uses: mukunku/tag-exists-action@v1.6.0
        id: check-tag
        with:
          tag: ${{ env.CURRENT_VERSION }}
          repo: ${{ github.repository }}
