on:
  push:
    branches:
      - 'feat/**'
      - 'features/**'
      - 'fix/**'
      - 'docs/**'
      - 'ci/**'
      - 'test/**'

name: 🔎 [VERSION] La version est elle différente ?
jobs:
  test-tag-availability:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Récupération de la version dans le `package.json` de la branche courante
        id: current_version
        run: |
          $version = (Get-Content package.json | ConvertFrom-Json).version
          echo "CURRENT_VERSION=$version" >> $env:GITHUB_OUTPUT
          echo "Version courante: $version"

      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Récupération de la version dans le `package.json` de la branche 'main'
        id: main_version
        run: |
          $version = (Get-Content package.json | ConvertFrom-Json).version
          echo "MAIN_VERSION=$version" >> $env:GITHUB_OUTPUT
          echo "Version main: $version"

      - name: Debug - Affichage des versions
        run: |
          echo "Current branch version: ${{ steps.current_version.outputs.CURRENT_VERSION }}"
          echo "Main branch version: ${{ steps.main_version.outputs.MAIN_VERSION }}"

      - name: Debug - Test de comparaison
        run: |
          $currentVersion = "${{ steps.current_version.outputs.CURRENT_VERSION }}"
          $mainVersion = "${{ steps.main_version.outputs.MAIN_VERSION }}"
          echo "Current Version: $currentVersion"
          echo "Main Version: $mainVersion"
          if ($currentVersion -eq $mainVersion) {
            echo "Les versions sont identiques"
            exit 1
          } else {
            echo "Les versions sont différentes"
          }

      - name: Comparaison des versions
        if: failure()
        run: |
          echo "La version dans package.json n'a pas été mise à jour. Veuillez mettre à jour la version. N'oubliez pas de vérifier le CHANGELOG et le README également."
          exit 1
